Metrics/LineLength:
  Max: 200
Style/ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'config/routes.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/tasks/*.rake'
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/devise.rb'
